services:
  webhook:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PYTHONPATH=/webhook_init
    container_name: webhook
    command: -verbose -hooks=/webhook/config/hooks.yaml -hotreload
    ports:
      - 9000:9000
    volumes:
      - ./volumes:/webhook
      - ./utils:/webhook_init/utils

